export const GET_MARKER_LOCATIONS_WEATHER = 'GET_MARKER_LOCATION_WEATHER';
export const GET_ENTERED_LOCATION_WEATHER = 'GET_ENTERED_LOCATION_WEATHER';
export const CLEAR_LAT_LNG = 'CLEAR_LAT_LNG';
export const ERROR = 'ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
